

export const VIEW = {
    FEED : 'FEED',
    FEATUREDTWEET: "FEATUREDTWEET",
    FEATUREDPROFILE : "FEATUREDUSER",
    FEATUREDPROFILEFOLLOWERS : 'FEATUREDPROFILEFOLLOWERS',
    FEATUREDPROFILEFOLLOWING : "FEATUREDPROFILEFOLLOWING",
    FEATUREDPROFILEFAVOURITES: "FEATUREDPROFILEFAVOURITES",
}